language: objective-c

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild -project CheatyXML.xcodeproj -scheme "CheatyXML" -destination "platform=iOS Simulator,name=iPhone 6" test