language: swift

osx_image: xcode9.3
xcode_sdk: iphonesimulator11.3

script: ./scripts/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    branch: master
    tags: true
