language: swift
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.2

stages:
  - test
  - name: deploy
    if: (tag =~ ^v) AND (branch = master)

jobs:
  include:
    - stage: test
      script: ./scripts/ci.sh
      after_success: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

    - stage: deploy
      before_script: ~/.rvm/scripts/rvm && rvm use default
      script: pod trunk push
